export enum RevocationReason {
  UNSPECIFIED = 'UNSPECIFIED',
  KEY_COMPROMISE = 'KEY_COMPROMISE',
  AFFILIATION_CHANGED = 'AFFILIATION_CHANGED',
  SUPERSEDED = 'SUPERSEDED',
  CESSATION_OF_OPERATION = 'CESSATION_OF_OPERATION',
  PRIVILEGE_WITHDRAWN = 'PRIVILEGE_WITHDRAWN'
}

