spring.application.name=public-key-infrastructure
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=DODATI NOV MEJL
spring.mail.password=app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=http://localhost:4200

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:pki_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (for development)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Database Initialization
spring.sql.init.mode=always
spring.sql.init.continue-on-error=false
spring.jpa.defer-datasource-initialization=true

# Encryption Configuration
app.encryption.master-key=dGVzdC1tYXN0ZXIta2V5LWZvci1kZXZlbG9wbWVudC1vbmx5LWRvLW5vdC11c2UtaW4tcHJvZHVjdGlvbg==
